### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [BlueDevelopersInc/DiscordSRVUtils#105] opened 2022-05-04 05:49 UTC
**Describe the bug**

If you have manually linked your account from console using command ``/discord link (minecraft username) (discord username)`` , commands like ``/level`` won't work and say 
``x Your account is not linked with any Minecraft Account. Use /discordsrv link in game to link your account``

**To Reproduce**
1. Run command - ``/discord link (minecraft username) (discord username)``
![IMG_20220504_111353.jpg](https://user-images.githubusercontent.com/97077949/166628365-0cc2be59-b645-4a01-a079-30477e47ef39.jpg)
2. Run command ``/level``
![IMG_20220504_111504.jpg](https://user-images.githubusercontent.com/97077949/166628433-7302aecd-dda2-42a9-a46f-e62acd785114.jpg)

**Expected behavior**
Command should work as normal since accounts have been linked

**Screenshots**
![IMG_20220504_111353.jpg](https://user-images.githubusercontent.com/97077949/166628484-3b41aa73-c09d-4ba0-a3c2-4cd65e754d77.jpg)
![IMG_20220504_111504.jpg](https://user-images.githubusercontent.com/97077949/166628495-a2f16acc-7f43-40bf-a61b-1f2b39e24496.jpg)

**Server Information:**
 - Version: 1.18.2
 - Software: Paper DEV 310
- Java 17

**Plugin Information:**
 - Version: 1.2.8
 - DiscordSRV Version: 1.25.1
 - Build Number: N/A

**Additional context**
N/A

**Comment by BlueTree242** [comment] 2022-05-04 06:04
![image](https://user-images.githubusercontent.com/69328929/166629968-03e626a6-ead9-46ed-8d31-03b41afcf5b9.png)
can't reproduce (this time was a debug think i was doing before, not related)

**Comment by PhoenixCodingStuff** [comment] 2022-05-04 06:14
Maybe because I'm the owner of the discord server?

**Comment by BlueTree242** [comment] 2022-05-04 06:17
No? Why would it be like that

**Comment by PhoenixCodingStuff** [comment] 2022-05-04 06:20
Okay , maybe thought that was the cause , I'll see what's causing the issue

**Comment by BlueTree242** [comment] 2022-05-04 06:21
Close this issue when ur done

**Closed** 2022-05-05 08:05 UTC
Labels: bug
