### ISSUE TITLE
[Feature Request] Add Lp Parent groups when ranking up for discord roles

### ISSUE THREAD

**Issue by shawn695** [BlueDevelopersInc/DiscordSRVUtils#123] opened 2022-09-26 17:24 UTC
for the leveling system that is based on chat in-game and in discord. players level up and recive discord roles. i would like that it would add corrisponding Lp Groups to match the roles in game at the same time

**Comment by Creeperz653** [comment] 2022-09-26 20:33
Cool

**Comment by BlueTree242** [comment] 2022-09-28 08:51
Duplicate of #99 actually, this will be closed you can track progress of this feature in the other issue

I will add ability to execute console commands, so just use the luckperms addparent command or smth

**Closed by BlueTree242** 2022-09-28 08:51 UTC
Labels: enhancement, Type: Suggestion, Status: Not Added, Working on it
